name: Regression
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
      - '!.github/workflows/Regression.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

env:
  BASE_BRANCH: ${{ github.base_ref || 'main' }}

jobs:
  regression-test:
    name: Regression Tests
    runs-on: ubuntu-22.04
    env:
      GEN: ninja
      BUILD_BENCHMARK: 1

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Checkout DuckDB to version
        shell: bash
        run: |
          cd duckdb
          git checkout $(cat ../.github/duckdb-version)

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build && pip install requests

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}
          save: ${{ github.ref == 'refs/heads/main' }}

      - name: Build current branch
        shell: bash
        run: |
          make release

      - name: Build base branch
        shell: bash
        run: |
          git worktree add ../ducklake-base origin/${{ env.BASE_BRANCH }}
          cd ../ducklake-base
          git submodule update --init --recursive
          cd duckdb && git checkout $(cat ../.github/duckdb-version) && cd ..
          BUILD_BENCHMARK=1 make release

      - name: Regression Test Insert
        shell: bash
        run: |
          python duckdb/scripts/regression/test_runner.py --old ../ducklake-base/build/release/benchmark/benchmark_runner --new build/release/benchmark/benchmark_runner --benchmarks .github/regression/insert.csv --verbose --threads 2 --nofail
